using TheBlock.UI.Menus;
using UnityEngine;
using UnityEngine.UIElements;

namespace TheBlock.Boot
{
    /// <summary>
    /// The boot screen - the port of <c>src/ui/loading-screen.ts</c> and <c>styles/loading.css</c>,
    /// dressed as key art.
    ///
    /// <b>The bar finally measures something.</b> That file's long comment is an apology: three.js's
    /// <c>DefaultLoadingManager</c> reports <c>itemsLoaded / itemsTotal</c>, the web build loads
    /// sequentially, so the first file to finish reports 1/1 and the bar sits pinned at 100% for the
    /// entire remaining download - "the worst possible lie to tell someone waiting". Its answer is a
    /// hand-counted list of milestones that must be kept in sync with <c>main.ts</c> by hand. Unity
    /// hands us <c>AsyncOperation.progress</c> over the whole scene, which is the number that file
    /// wanted and could not have.
    ///
    /// <b>There is no Play button.</b> <c>waitForPlay()</c> exists to harvest a user gesture,
    /// because a browser will not start an <c>AudioContext</c> without one - its own comment says
    /// so at the click handler ("first user gesture - also primes the shared AudioContext"). Unity
    /// has no autoplay policy, so the button is scar tissue and the bar simply finishes.
    ///
    /// <b>The art is the layout.</b> The cover carries its own wordmark, so the UI does not draw a
    /// second one; the bar, the status and the tip dock along the bottom over a scrim, which is the
    /// shape every shipped game's loading screen has for the same reason - the art needs the frame
    /// and the text needs a readable backing. With no cover imported the screen falls back to the
    /// plain dark backdrop and its own wordmark, so this never hard-depends on an asset.
    ///
    /// <see cref="Fail"/> survives, unchanged in spirit: a boot that dies has to read as an error
    /// rather than hang at "Loading…".
    /// </summary>
    [RequireComponent(typeof(UIDocument))]
    public class LoadingScreen : MonoBehaviour
    {
        /// <summary>
        /// Where the cover lives, <c>Resources.Load</c>-relative - the file is
        /// <c>Assets/Resources/UI/LoadingArt.png</c>.
        ///
        /// <b>Resources rather than a serialized reference.</b> This scene is generated by
        /// <c>MenuBuilder.BuildBootScene</c>, so anything wired into the component by hand is wiped
        /// the next time someone runs <b>The Block → Build Menus</b>. A path in code survives that,
        /// and it is one asset on a screen that draws nothing else.
        /// </summary>
        [SerializeField] private string artResourcePath = "UI/LoadingArt";

        [Tooltip("Where the crop sits when the cover is wider than the window, 0 = left edge, " +
                 "1 = right edge. The cover's painted wordmark is on its right, so the crop is " +
                 "biased that way rather than centred - centred clips it on a 16:9 screen.")]
        [SerializeField, Range(0f, 1f)] private float artAnchorX = 0.70f;

        [SerializeField, Range(0f, 1f)] private float artAnchorY = 0.5f;

        [Tooltip("Seconds the slow zoom takes to run its full range. Longer than any boot - the " +
                 "point is that it never visibly arrives anywhere.")]
        [SerializeField] private float kenBurnsSeconds = 20f;

        [Tooltip("Seconds each tip is held before the next one.")]
        [SerializeField] private float tipSeconds = 3.2f;

        /// <summary>
        /// Every line here has to be true, and that is the same rule <see cref="ControlsGuide"/>
        /// enforces on itself ("it is the one screen a stuck player reads"). A loading tip is read
        /// in exactly the state where the player cannot check it, so a stale one is worse here than
        /// anywhere else in the shell. Each of these is a binding or a rule that exists today.
        /// </summary>
        private static readonly string[] Tips =
        {
            "Hold Shift to sprint on foot. Alt is a jog, for when you only need to close the gap.",
            "Press E at any vehicle to take it, and E again to get out.",
            "Lose the cops and your stars fade one at a time. Staying in their sight resets it.",
            "Hold Space at a gas pump to refuel. Watch the gauge before a long run.",
            "M opens the map. Every job, store and stop is marked on it.",
            "Drive into the auto shop and press C to change your car's color.",
            "R flips a vehicle back onto its wheels when a chase goes wrong.",
            "Power-ups you buy at the 7-Eleven go on keys 1 to 4.",
        };

        private VisualElement _screen;
        private VisualElement _art;
        private VisualElement _fill;
        private Label _status;
        private Label _percent;
        private Label _tip;

        private Vector2 _artSize;
        private float _elapsed;
        private float _tipTimer;
        private int _tipIndex;
        private float _target;
        private float _shown;
        private bool _failed;

        private void Awake() => Build();

        private void Build()
        {
            if (_fill != null) return;

            var root = GetComponent<UIDocument>()?.rootVisualElement;
            if (root == null) return;

            _screen = MenuStyle.Overlay("loading-screen", opaque: true);
            _screen.style.display = DisplayStyle.Flex;

            // The zoom pushes the cover past the element's own edges; without this it paints over
            // the whole panel and the crop stops meaning anything.
            _screen.style.overflow = Overflow.Hidden;
            root.Add(_screen);

            var art = Resources.Load<Texture2D>(artResourcePath);
            if (art != null)
            {
                _artSize = new Vector2(art.width, art.height);

                _art = new VisualElement { name = "loading-art" };
                _art.style.position = Position.Absolute;
                _art.style.backgroundImage = new StyleBackground(art);

                // Starts slightly in, so the horizontal drift below can never expose an edge.
                _art.style.scale = new Scale(new Vector3(1.03f, 1.03f, 1f));
                _art.style.opacity = 0f; // faded in over the first frames - see Update
                _screen.Add(_art);

                _screen.Add(BuildScrim());

                // The cover paints "THE BLOCK / AN OPEN-WORLD GAME" itself. A UI wordmark on top of
                // that is the same title twice.
                _screen.RegisterCallback<GeometryChangedEvent>(_ => LayoutArt());
            }
            else
            {
                // No cover imported: the pre-art screen, unchanged, rather than a blank rectangle.
                _screen.Add(MenuStyle.Wordmark("The Block", 44f));
            }

            _screen.Add(BuildDock());
            NextTip();
        }

        /// <summary>Rows in the scrim ramp - see <see cref="BuildScrim"/>.</summary>
        private const int ScrimRows = 48;

        /// <summary>
        /// The readability scrim: transparent at the top, black at the bottom, over the lower 46%
        /// of the screen. UI Toolkit has no gradient at the style level -
        /// <see cref="MenuStyle"/> says so and flattens two CSS gradients for exactly that reason.
        ///
        /// <b>Stacked strips, and the obvious one-texture version was tried first and abandoned.</b>
        /// A 1x256 alpha ramp as a <c>background-image</c> is not drawn to fit its element: measured
        /// off a real panel render, the box was the correct 337 x full-width and the ramp inside it
        /// ran over roughly 190 units starting a third of the way down, putting 0.22 of alpha under
        /// the tip row where the curve says 0.73. Setting <c>backgroundSize</c> to 100% 100%,
        /// <c>backgroundRepeat</c> to no-repeat and <c>backgroundPositionY</c> to top - all three,
        /// explicitly - changed the render by not one pixel.
        ///
        /// Forty-eight strips have no such semantics to get wrong: each is a flex row with a solid
        /// colour, they do not overlap, so the whole ramp is one screen of fill and no overdraw at
        /// all. The step between rows is about 0.02 of alpha, which is under a level of 8-bit output
        /// across most of the curve and invisible over artwork.
        /// </summary>
        private VisualElement BuildScrim()
        {
            var scrim = new VisualElement { name = "loading-scrim" };
            scrim.style.position = Position.Absolute;
            scrim.style.left = 0f;
            scrim.style.right = 0f;
            scrim.style.bottom = 0f;
            scrim.style.height = Length.Percent(46f);
            scrim.style.flexDirection = FlexDirection.Column;

            for (int i = 0; i < ScrimRows; i++)
            {
                // Centre of the row, so the first strip is not fully transparent and the last is not
                // fully opaque - the ramp reads as continuous rather than as a stack.
                var t = (i + 0.5f) / ScrimRows;

                // A ramp over the TOP 55% of the band and a flat floor under it, rather than one
                // curve across the whole thing. The text does not sit at the bottom of the band -
                // the tip row is about 60% of the way down it - so a curve that only reaches full
                // strength at the very bottom spends its darkness below everything that needed it.
                //
                // Measured, on the beach sand that is the brightest thing under the dock: a single
                // smoothstep to 0.94 left the tip row's background at sRGB 139, which is still
                // half-bright. Reaching 0.95 by 55% of the band puts it at 63, and the fade above
                // is still 273 px tall - wide enough that its top edge is not a visible line.
                //
                // Smoothstep rather than linear for that fade, for the same reason.
                var u = Mathf.Clamp01(t / 0.55f);
                var a = u * u * (3f - 2f * u) * 0.95f;

                var row = new VisualElement();
                row.style.flexGrow = 1f;

                // Black, not the near-black (4, 6, 9) this started as. Measured off a panel render:
                // those three came back at linear (0.016, 0.020, 0.031) - i.e. UNCONVERTED, drawn at
                // sRGB 0.135, LIGHTER than the 0.078 backdrop behind them. That is the gamma trap
                // MenuStyle's palette comment describes. Zero is zero in both spaces, so the
                // question does not arise, and over key art nobody can tell the two apart.
                row.style.backgroundColor = new Color(0f, 0f, 0f, a);
                scrim.Add(row);
            }

            return scrim;
        }

        /// <summary>The bottom furniture: the tip, the status row, the bar.</summary>
        private VisualElement BuildDock()
        {
            var dock = new VisualElement { name = "loading-dock" };
            dock.style.position = Position.Absolute;
            dock.style.left = 0f;
            dock.style.right = 0f;
            dock.style.bottom = 0f;
            dock.style.paddingLeft = 64f;
            dock.style.paddingRight = 64f;
            dock.style.paddingBottom = 52f;

            // ── the tip ───────────────────────────────────────────────────────────────────────
            var tipRow = new VisualElement();
            tipRow.style.flexDirection = FlexDirection.Row;
            tipRow.style.alignItems = Align.Center;
            tipRow.style.marginBottom = 18f;
            dock.Add(tipRow);

            var tag = new Label("TIP");
            tag.style.fontSize = 11f;
            tag.style.letterSpacing = 2f;
            tag.style.unityFontStyleAndWeight = FontStyle.Bold;
            tag.style.color = MenuStyle.AccentInk;
            tag.style.backgroundColor = MenuStyle.Accent;
            tag.style.paddingLeft = 8f;
            tag.style.paddingRight = 6f;
            tag.style.paddingTop = 3f;
            tag.style.paddingBottom = 3f;
            tag.style.marginRight = 12f;
            tag.style.flexShrink = 0f;
            MenuStyle.SetBorder(tag, Color.clear, 0f, 4f);
            tipRow.Add(tag);

            _tip = new Label(string.Empty);
            _tip.style.fontSize = 15f;
            _tip.style.color = MenuStyle.Ui(1f, 1f, 1f, 0.72f);
            _tip.style.whiteSpace = WhiteSpace.Normal;
            _tip.style.flexShrink = 1f;
            tipRow.Add(_tip);

            // ── status left, percentage right ─────────────────────────────────────────────────
            var statusRow = new VisualElement();
            statusRow.style.flexDirection = FlexDirection.Row;
            statusRow.style.alignItems = Align.FlexEnd;
            statusRow.style.justifyContent = Justify.SpaceBetween;
            statusRow.style.marginBottom = 10f;
            dock.Add(statusRow);

            _status = new Label("LOADING…");
            _status.style.fontSize = 12f;
            _status.style.letterSpacing = 3f;
            _status.style.unityFontStyleAndWeight = FontStyle.Bold;
            _status.style.color = MenuStyle.Ui(1f, 1f, 1f, 0.62f);
            statusRow.Add(_status);

            _percent = new Label("0%");
            _percent.style.fontSize = 22f;
            _percent.style.unityFontStyleAndWeight = FontStyle.Bold;
            _percent.style.color = Color.white;
            statusRow.Add(_percent);

            // ── the bar ───────────────────────────────────────────────────────────────────────
            //
            // Full-width and 5 px rather than the web's centred 420x10 pill. The centred pill was
            // the whole composition there; here it is the base of one, and a hairline that spans the
            // frame is what reads as deliberate against a full-bleed image.
            var track = new VisualElement { name = "loading-bar" };
            track.style.height = 5f;
            track.style.backgroundColor = MenuStyle.Ui(1f, 1f, 1f, 0.16f);
            track.style.overflow = Overflow.Hidden;
            MenuStyle.SetBorder(track, Color.clear, 0f, 3f);
            dock.Add(track);

            _fill = new VisualElement { name = "loading-bar-fill" };
            _fill.style.width = Length.Percent(0f);
            _fill.style.height = Length.Percent(100f);
            _fill.style.backgroundColor = MenuStyle.Accent;
            MenuStyle.SetBorder(_fill, Color.clear, 0f, 3f);
            track.Add(_fill);

            return dock;
        }

        /// <summary>
        /// CSS <c>background-size: cover</c>, by hand.
        ///
        /// UI Toolkit does have a <c>backgroundSize</c>, but the anchor it pairs with is the piece
        /// that matters here - the cover is 2.36:1 against a 16:9 window, so a quarter of its width
        /// is off-screen and WHICH quarter decides whether the painted wordmark survives. Sizing the
        /// element myself makes the anchor an explicit number instead of a keyword.
        /// </summary>
        private void LayoutArt()
        {
            if (_art == null || _artSize.x <= 0f || _artSize.y <= 0f) return;

            var box = _screen.resolvedStyle;
            if (float.IsNaN(box.width) || box.width <= 0f || box.height <= 0f) return;

            var scale = Mathf.Max(box.width / _artSize.x, box.height / _artSize.y);
            var w = _artSize.x * scale;
            var h = _artSize.y * scale;

            _art.style.width = w;
            _art.style.height = h;
            _art.style.left = (box.width - w) * artAnchorX;
            _art.style.top = (box.height - h) * artAnchorY;
        }

        private void Update()
        {
            // Unscaled throughout: this scene runs before anything touches timeScale, but the world
            // it hands over to opens frozen, and a screen that stops animating on the last frame of
            // a load reads as a hang.
            var dt = Time.unscaledDeltaTime;
            _elapsed += dt;

            if (_art != null)
            {
                // Fade in. The boot camera clears to the same backdrop the fallback uses, so this
                // resolves the cover out of the dark rather than cutting to it on frame one.
                if (_art.style.opacity.value < 1f)
                    _art.style.opacity = Mathf.Clamp01(_elapsed / 0.45f);

                // Ken Burns. Eased so it is quickest at the start, where it is least likely to be
                // mistaken for the screen having finished moving.
                var t = kenBurnsSeconds > 0f ? Mathf.Clamp01(_elapsed / kenBurnsSeconds) : 0f;
                //
                // The zoom range is bounded by the cover's own wordmark, not by taste. At anchor
                // 0.70 on 16:9 the crop shows image x 18.7%-92.0% at 1.03 and 21.5%-91.0% at 1.09,
                // and the painted "BLOCK" ends at 89.5% - so 1.09 is the last stop that still keeps
                // the K off the right edge. Widening it is not a free knob.
                var eased = 1f - (1f - t) * (1f - t);
                var zoom = Mathf.Lerp(1.03f, 1.09f, eased);
                _art.style.scale = new Scale(new Vector3(zoom, zoom, 1f));
                _art.style.translate = new Translate(Mathf.Lerp(10f, -10f, eased), 0f);
            }

            if (!_failed)
            {
                _tipTimer += dt;
                if (_tipTimer >= Mathf.Max(1f, tipSeconds)) NextTip();

                // The bar chases the load rather than snapping to it. Unity's progress arrives in
                // steps, and the last one is 0.99 → 1.00 inside holdAtFull's 0.25 s, so the floor
                // speed is what guarantees the bar is actually full when the world swaps in.
                var speed = Mathf.Max(0.6f, Mathf.Abs(_target - _shown) * 4f);
                _shown = Mathf.MoveTowards(_shown, _target, speed * dt);
                Paint(_shown);
            }
        }

        private void NextTip()
        {
            _tipTimer = 0f;
            if (_tip == null || Tips.Length == 0) return;

            // A random first tip, then in order. Same boot twice should not read the same line
            // twice, and the sequence after it still cannot repeat one before showing the rest.
            if (_tip.text.Length == 0) _tipIndex = Random.Range(0, Tips.Length);
            else _tipIndex = (_tipIndex + 1) % Tips.Length;

            _tip.text = Tips[_tipIndex];
        }

        private void Paint(float fraction)
        {
            var percent = Mathf.RoundToInt(Mathf.Clamp01(fraction) * 100f);
            if (_fill != null) _fill.style.width = Length.Percent(percent);
            if (_percent != null) _percent.text = $"{percent}%";
        }

        /// <summary>Paints the bar. <paramref name="fraction"/> is 0-1; the label sits beside it.</summary>
        public void SetProgress(float fraction, string label)
        {
            if (_failed) return; // a dead boot must not keep animating as if it were fine
            Build();

            _target = Mathf.Clamp01(fraction);
            if (_status != null) _status.text = label?.ToUpperInvariant() ?? "LOADING…";
        }

        /// <summary>
        /// Boot died. The bar goes red and full and the reason replaces the tip - the web's
        /// <c>#loading-screen.failed</c>, and the first error wins so a cascade cannot overwrite the
        /// cause.
        /// </summary>
        public void Fail(string message)
        {
            if (_failed) return;
            _failed = true;
            Build();

            if (_fill != null)
            {
                _fill.style.width = Length.Percent(100f);
                _fill.style.backgroundColor = MenuStyle.Ui(0.84f, 0.27f, 0.27f);
            }

            if (_percent != null) _percent.style.display = DisplayStyle.None;
            if (_status != null)
            {
                _status.text = "BOOT FAILED";
                _status.style.color = MenuStyle.Ui(1f, 0.71f, 0.71f);
            }

            if (_tip != null)
            {
                _tip.text = message;
                _tip.style.color = MenuStyle.Ui(1f, 0.82f, 0.82f);
            }

            Debug.LogError($"LoadingScreen: {message}");
        }
    }
}
