using System.Collections.Generic;
using System.Linq;
using System.Text;
using TheBlock.Npc;
using UnityEditor;
using UnityEngine;

namespace TheBlock.EditorTools
{
    /// <summary>
    /// Writes the ragdoll rig into every body that can be knocked down - <b>The Block → Build
    /// Ragdolls</b>. U35a.
    ///
    /// <b>Why this exists rather than the Ragdoll Wizard.</b> Unity ships one
    /// (<c>GameObject → 3D Object → Ragdoll…</c>) and it would do this job once, by hand, per prefab,
    /// with nine drag-and-drops each and no record of what was dropped where. This project has nine
    /// bodies, every other prefab in it is generated by a menu item, and two of those menu items -
    /// <c>Build Pedestrians</c> and <c>Build Characters</c> - REPLACE the prefabs this writes into.
    /// A hand-built rig would survive until the next time either was run, which is exactly the story
    /// of how U34 found <c>CrashSensor</c> attached to nothing. Both builders call this at their tail
    /// for that reason.
    ///
    /// <b>Eleven bodies, ten joints - the Wizard's own skeleton</b>, because it is the one every
    /// animator, every asset pack and every tutorial assumes: pelvis, chest, head, two arms in two
    /// pieces, two legs in two pieces. Hands, feet and fingers are left as passengers of their parent
    /// bone: a foot shell adds two more bodies per rig for a part of the body nobody watches, and the
    /// ankle is where ragdolls jitter.
    ///
    /// <b>Every dimension is MEASURED off the rig, never typed in.</b> The six pedestrians are six
    /// different Mixamo uploads and the three player characters are three more; their bones sit in
    /// different places and two of them are not 1.70 m tall in their own units at all (memory:
    /// <c>root-motion-on-a-scaled-child</c> - Remy's avatar is 4.20 m and is drawn at 0.405×). So a
    /// shell's length is the distance to the next bone, and its radius is a fraction of that length.
    /// A typed radius would be a tenth of a metre on one body and a third of one on another.
    ///
    /// <b>Masses are typed in, and that is the opposite call for a reason.</b> A Rigidbody's mass is
    /// in kilograms, and a person weighs what a person weighs whatever units their FBX was saved in.
    /// The set below sums to about 64 kg. Port rule 2 governs everything else here: not one number
    /// came from the web build, because Rapier never had a ragdoll to tune.
    /// </summary>
    public static class RagdollBuilder
    {
        private const string PedFolder = "Assets/Prefabs/Npc";
        private const string CharacterFolder = "Assets/Prefabs/Characters";

        // --- the skeleton -----------------------------------------------------------------------

        /// <summary>
        /// One simulated bone: which Humanoid bone it is, which bone gives it its length, what it
        /// weighs, and how its joint may move.
        ///
        /// <c>Parent</c> is the bone whose BODY this one hangs off - not the transform's parent. A
        /// forearm hangs off an upper arm even though three unmapped twist bones may sit between them
        /// in the hierarchy, and that is normal for a Mixamo rig.
        /// </summary>
        private readonly struct Bone
        {
            public readonly HumanBodyBones Self;
            public readonly HumanBodyBones Tip;      // the bone that gives Self its length
            public readonly HumanBodyBones Parent;   // the body this one joints to; Self for the root
            public readonly float Mass;
            public readonly float RadiusOfLength;    // shell radius as a fraction of the bone's length
            public readonly Hinge Joint;

            public Bone(
                HumanBodyBones self, HumanBodyBones tip, HumanBodyBones parent, float mass,
                float radiusOfLength, Hinge joint)
            {
                Self = self;
                Tip = tip;
                Parent = parent;
                Mass = mass;
                RadiusOfLength = radiusOfLength;
                Joint = joint;
            }

            public bool IsRoot => Self == Parent;
        }

        /// <summary>
        /// How a joint is allowed to move. The names are anatomy, not physics - each maps to one
        /// <c>CharacterJoint</c> whose twist axis and limits are chosen in <see cref="Configure"/>.
        /// </summary>
        private enum Hinge
        {
            None,
            Waist,
            Neck,
            Shoulder,
            Elbow,
            Hip,
            Knee,
        }

        /// <summary>
        /// The rig, parents before children - <see cref="Build"/> relies on the order, because a
        /// joint cannot be made until the body it connects to exists.
        /// </summary>
        private static readonly Bone[] Skeleton =
        {
            // The pelvis is measured to the CHEST, not to the spine directly above it: on a Mixamo rig
            // those two bones are 12 cm apart, which builds a pelvis the thickness of a belt and lets
            // the hips fall through their own thighs at the first hard landing.
            new(HumanBodyBones.Hips, HumanBodyBones.Chest, HumanBodyBones.Hips, 12f, 0.62f, Hinge.None),
            new(HumanBodyBones.Chest, HumanBodyBones.Head, HumanBodyBones.Hips, 16f, 0.40f, Hinge.Waist),
            new(HumanBodyBones.Head, HumanBodyBones.Head, HumanBodyBones.Chest, 5f, 0f, Hinge.Neck),

            new(HumanBodyBones.LeftUpperArm, HumanBodyBones.LeftLowerArm, HumanBodyBones.Chest, 2.2f, 0.22f, Hinge.Shoulder),
            new(HumanBodyBones.LeftLowerArm, HumanBodyBones.LeftHand, HumanBodyBones.LeftUpperArm, 1.6f, 0.20f, Hinge.Elbow),
            new(HumanBodyBones.RightUpperArm, HumanBodyBones.RightLowerArm, HumanBodyBones.Chest, 2.2f, 0.22f, Hinge.Shoulder),
            new(HumanBodyBones.RightLowerArm, HumanBodyBones.RightHand, HumanBodyBones.RightUpperArm, 1.6f, 0.20f, Hinge.Elbow),

            new(HumanBodyBones.LeftUpperLeg, HumanBodyBones.LeftLowerLeg, HumanBodyBones.Hips, 7.5f, 0.20f, Hinge.Hip),
            new(HumanBodyBones.LeftLowerLeg, HumanBodyBones.LeftFoot, HumanBodyBones.LeftUpperLeg, 4f, 0.17f, Hinge.Knee),
            new(HumanBodyBones.RightUpperLeg, HumanBodyBones.RightLowerLeg, HumanBodyBones.Hips, 7.5f, 0.20f, Hinge.Hip),
            new(HumanBodyBones.RightLowerLeg, HumanBodyBones.RightFoot, HumanBodyBones.RightUpperLeg, 4f, 0.17f, Hinge.Knee),
        };

        /// <summary>The head is a sphere, and its radius is this much of the neck-to-crown distance.</summary>
        private const float HeadRadiusOfNeck = 0.62f;

        /// <summary>
        /// Ceiling on how fast PhysX may push two overlapping shells apart.
        ///
        /// <b>This one line is the difference between a ragdoll and a firework.</b> A rig built in a
        /// T-pose has shells that touch, and the first frame of simulation resolves those overlaps at
        /// whatever speed it takes - which, unclamped, is tens of metres per second in one step. Every
        /// "my ragdoll explodes" is this, and the joints get blamed.
        /// </summary>
        private const float MaxDepenetration = 2.5f;

        // --- the menu item ----------------------------------------------------------------------

        [MenuItem("The Block/Build Ragdolls", priority = 23)]
        public static void BuildMenu() => Build();

        /// <summary>
        /// Rigs every pedestrian and every player character. Idempotent: an existing rig is stripped
        /// first, so this is safe to run after any change to the skeleton table above.
        /// </summary>
        public static string Build()
        {
            var log = new StringBuilder();
            int done = 0;
            int attempted = 0;

            foreach (var path in Targets())
            {
                attempted++;
                if (BuildOne(path, log)) done++;
            }

            AssetDatabase.SaveAssets();

            var report = $"RagdollBuilder - {done}/{attempted} body/bodies rigged\n{log}";
            if (done < attempted) Debug.LogWarning(report);
            else Debug.Log(report);
            return report;
        }

        /// <summary>
        /// Every prefab that can be knocked down: the six faces in the crowd and the three the player
        /// wears. <b>Not the cop and not the thief</b> - neither is ever run over (the officer is
        /// <c>CopOfficer</c>'s, driven by the police system, and the thief is a mission actor), so
        /// eleven bodies each would be paid for a reaction that cannot happen.
        /// </summary>
        private static IEnumerable<string> Targets()
        {
            foreach (var name in PeopleImporter.Names)
            {
                var path = $"{PedFolder}/Ped_{name}.prefab";
                if (AssetDatabase.LoadAssetAtPath<GameObject>(path) != null) yield return path;
            }

            foreach (var guid in AssetDatabase.FindAssets("t:Prefab", new[] { CharacterFolder }))
                yield return AssetDatabase.GUIDToAssetPath(guid);
        }

        private static bool BuildOne(string path, StringBuilder log)
        {
            var name = System.IO.Path.GetFileNameWithoutExtension(path);
            var contents = PrefabUtility.LoadPrefabContents(path);
            if (contents == null)
            {
                log.AppendLine($"{name,-14} SKIPPED - could not open {path}");
                return false;
            }

            try
            {
                var animator = contents.GetComponentInChildren<Animator>(true);
                if (animator == null || animator.avatar == null || !animator.avatar.isHuman)
                {
                    log.AppendLine($"{name,-14} SKIPPED - no Humanoid Animator, so there are no bones to find");
                    return false;
                }

                Strip(animator.transform);

                if (!Rig(animator, out var bodies, out var shells, out var report))
                {
                    log.AppendLine($"{name,-14} SKIPPED - {report}");
                    return false;
                }

                if (!contents.TryGetComponent<Ragdoll>(out var ragdoll))
                    ragdoll = contents.AddComponent<Ragdoll>();

                ragdoll.Configure(animator, bodies[0], bodies, shells);

                PrefabUtility.SaveAsPrefabAsset(contents, path);
                log.AppendLine($"{name,-14} {report}");
                return true;
            }
            finally
            {
                PrefabUtility.UnloadPrefabContents(contents);
            }
        }

        // --- building ---------------------------------------------------------------------------

        /// <summary>
        /// Removes a previous rig, so a rebuild replaces rather than doubles.
        ///
        /// Joints first and in their own pass: destroying a Rigidbody that a joint still points at
        /// leaves the joint referencing nothing, and <c>DestroyImmediate</c> on a component the editor
        /// is mid-way through validating is the kind of thing that logs from inside PhysX.
        ///
        /// It walks the SKELETON only - <paramref name="skeleton"/> is the Animator's transform, so
        /// the pedestrian root's own capsule and kinematic Rigidbody (<c>NpcBuilder</c>'s, and
        /// load-bearing) are outside the sweep by construction.
        /// </summary>
        private static void Strip(Transform skeleton)
        {
            foreach (var joint in skeleton.GetComponentsInChildren<CharacterJoint>(true))
                Object.DestroyImmediate(joint);

            foreach (var body in skeleton.GetComponentsInChildren<Rigidbody>(true))
            {
                if (body.transform == skeleton) continue;
                Object.DestroyImmediate(body);
            }

            foreach (var shell in skeleton.GetComponentsInChildren<Collider>(true))
            {
                if (shell.transform == skeleton) continue;
                Object.DestroyImmediate(shell);
            }
        }

        private static bool Rig(Animator animator, out Rigidbody[] bodies, out Collider[] shells, out string report)
        {
            bodies = null;
            shells = null;
            report = null;

            var described = Described(animator);

            var bones = new Dictionary<HumanBodyBones, Transform>();
            foreach (var entry in Skeleton)
            {
                var transform = Resolve(animator, described, entry.Self);
                if (transform == null)
                {
                    report = $"the avatar has no {entry.Self} bone";
                    return false;
                }

                bones[entry.Self] = transform;

                // The TIPS as well, and they are the reason this is a second lookup rather than the
                // same one: a shin's length is the distance to the FOOT and a forearm's is the
                // distance to the HAND, and neither is a simulated bone. Resolved only against the
                // rig's own eleven, both came back null and fell through to a 20 cm stub pointing at
                // the sky - which built every lower leg in the game as a stunted capsule at the wrong
                // angle, and looked plausible enough in a table of numbers to nearly ship.
                if (bones.ContainsKey(entry.Tip)) continue;
                var tip = Resolve(animator, described, entry.Tip);
                if (tip != null) bones[entry.Tip] = tip;
            }

            int shellLayer = LayerMask.NameToLayer(Ragdoll.ShellLayer);
            var right = animator.transform.right;
            var forward = animator.transform.forward;

            var builtBodies = new List<Rigidbody>(Skeleton.Length);
            var builtShells = new List<Collider>(Skeleton.Length);
            var byBone = new Dictionary<HumanBodyBones, Rigidbody>();
            float mass = 0f;

            foreach (var entry in Skeleton)
            {
                var bone = bones[entry.Self];

                var body = bone.gameObject.AddComponent<Rigidbody>();
                body.mass = entry.Mass;
                body.linearDamping = 0.05f;
                body.angularDamping = 0.06f;

                // ⚠ NONE, and it is switched on only while the body simulates - see Ragdoll.Activate.
                //
                // Interpolation is a write in the direction nobody expects: PhysX → Transform, every
                // frame, whether the body is kinematic or not. On a kinematic bone that no physics
                // step has ever moved, PhysX's pose is the one the PREFAB was saved in - so an
                // interpolated rig drags every bone of every pedestrian back to the prefab's origin
                // while they walk. Measured on a pedestrian standing at (10.8, 0, −159.4) with their
                // hips reading (0, 0.83, 0): the whole crowd smeared to the middle of the map, and
                // nothing had been run over.
                body.interpolation = RigidbodyInterpolation.None;

                // Speculative rather than full continuous: a body launched at 11 m/s covers 22 cm in a
                // step and the road is a thin mesh, so discrete really does let a hip through it -
                // but eleven swept bodies per corpse is a cost with no ceiling. Speculative is the
                // one that is cheap AND does not tunnel.
                body.collisionDetectionMode = CollisionDetectionMode.ContinuousSpeculative;
                body.maxDepenetrationVelocity = MaxDepenetration;
                body.isKinematic = true;

                var shell = Shell(entry, bone, bones, animator.transform);
                if (shellLayer >= 0) bone.gameObject.layer = shellLayer;
                shell.enabled = false;

                builtBodies.Add(body);
                builtShells.Add(shell);
                byBone[entry.Self] = body;
                mass += entry.Mass;
            }

            foreach (var entry in Skeleton)
            {
                if (entry.IsRoot) continue;

                var bone = bones[entry.Self];
                var joint = bone.gameObject.AddComponent<CharacterJoint>();
                joint.connectedBody = byBone[entry.Parent];
                Configure(joint, entry, bone, bones, right, forward);
            }

            bodies = builtBodies.ToArray();
            shells = builtShells.ToArray();
            report =
                $"{bodies.Length} bodies, {bodies.Length - 1} joints, {mass:0.#} kg | " +
                $"scale {animator.transform.lossyScale.x:0.###}";
            return true;
        }

        /// <summary>One bone: the Animator's answer when it has one, the Avatar's table when it does not.</summary>
        private static Transform Resolve(
            Animator animator, Dictionary<HumanBodyBones, Transform> described, HumanBodyBones bone)
        {
            var found = animator.GetBoneTransform(bone);
            if (found != null) return found;
            return described.TryGetValue(bone, out var fallback) ? fallback : null;
        }

        /// <summary>
        /// Every Humanoid bone this rig needs, read off the AVATAR rather than asked of the Animator.
        ///
        /// <b>Why it cannot just be <c>GetBoneTransform</c>, which is the obvious call and the one
        /// tried first.</b> That method answers out of the Animator's live bind, and an Animator
        /// inside <c>PrefabUtility.LoadPrefabContents</c> is in a preview scene that never ticks - so
        /// on the six pedestrians, whose Animator sits on a nested model-prefab instance, every bone
        /// came back null and the whole crowd reported "the avatar has no Hips bone". The three player
        /// bodies, whose Animator is the prefab root, happened to answer. A silent difference between
        /// two prefab shapes is exactly the kind of thing that would have shipped as "ragdolls only
        /// work for the player".
        ///
        /// The Avatar's <c>humanDescription</c> is a plain asset table - the Humanoid name against the
        /// TRANSFORM name it was mapped to - and it is correct with nothing initialised at all.
        /// </summary>
        private static Dictionary<HumanBodyBones, Transform> Described(Animator animator)
        {
            var found = new Dictionary<HumanBodyBones, Transform>();
            var avatar = animator.avatar;
            if (avatar == null || !avatar.isHuman) return found;

            var transforms = new Dictionary<string, Transform>();
            foreach (var child in animator.GetComponentsInChildren<Transform>(true))
                transforms.TryAdd(child.name, child);

            var mapped = new Dictionary<string, string>();
            foreach (var human in avatar.humanDescription.human)
                mapped[human.humanName] = human.boneName;

            for (int i = 0; i < (int)HumanBodyBones.LastBone; i++)
            {
                var name = HumanTrait.BoneName[i];
                if (!mapped.TryGetValue(name, out var boneName)) continue;
                if (!transforms.TryGetValue(boneName, out var bone)) continue;
                found[(HumanBodyBones)i] = bone;
            }

            return found;
        }

        /// <summary>
        /// The shell for one bone: a sphere for the head, a box for the pelvis and chest, a capsule
        /// for anything with a length.
        ///
        /// <b>Every size is computed in world metres and then divided by the bone's own scale.</b>
        /// Collider dimensions are local, and these skeletons hang under a visual child scaled to put
        /// the character at 1.70 m - so a radius written straight in would be as wrong as the scale is
        /// far from 1, which on Remy is a factor of 2.5.
        /// </summary>
        private static Collider Shell(
            in Bone entry, Transform bone, Dictionary<HumanBodyBones, Transform> bones, Transform root)
        {
            float scale = Mathf.Max(0.0001f, Mathf.Abs(bone.lossyScale.x));

            if (entry.Self == HumanBodyBones.Head)
            {
                var head = bone.gameObject.AddComponent<SphereCollider>();

                // The crown is not a bone on a Mixamo rig (the end site is stripped on import), so the
                // head's size is taken from the neck below it - the one measurement that is always
                // there. Half a head above the neck joint is where a skull's centre is.
                var neck = bones[HumanBodyBones.Chest];
                float reach = Vector3.Distance(bone.position, neck.position) * HeadRadiusOfNeck;
                float radius = Mathf.Max(0.06f, reach * 0.5f);

                head.radius = radius / scale;
                head.center = bone.InverseTransformPoint(bone.position + root.up * (radius * 0.9f));
                return head;
            }

            var tip = bones.TryGetValue(entry.Tip, out var found) ? found : null;
            var toTip = tip != null ? tip.position - bone.position : root.up * 0.2f;
            float length = Mathf.Max(0.05f, toTip.magnitude);

            if (entry.Self == HumanBodyBones.Hips || entry.Self == HumanBodyBones.Chest)
            {
                var box = bone.gameObject.AddComponent<BoxCollider>();

                // The torso's WIDTH is the span of the pair of limbs that hang off it - hips from the
                // thighs, chest from the shoulders - which is the only honest measure of how broad a
                // given character is. A fraction of the height would make a stocky rig narrow.
                float width = entry.Self == HumanBodyBones.Hips
                    ? Vector3.Distance(bones[HumanBodyBones.LeftUpperLeg].position, bones[HumanBodyBones.RightUpperLeg].position) * 1.6f
                    : Vector3.Distance(bones[HumanBodyBones.LeftUpperArm].position, bones[HumanBodyBones.RightUpperArm].position) * 1.05f;

                width = Mathf.Max(width, length * 0.5f);
                float depth = width * 0.6f;

                var centreWorld = bone.position + toTip.normalized * (length * 0.5f);

                // Written into the bone's own frame, and the axis order matters: the box is authored
                // as (character-right, along-the-bone, character-forward) and the bone's local axes
                // are none of those on a Mixamo rig. LocalSize projects it rather than assuming - and
                // it takes WORLD metres, because InverseTransformVector already divides by the scale
                // this method has to divide by by hand everywhere else.
                box.center = bone.InverseTransformPoint(centreWorld);
                box.size = LocalSize(bone, root.right * width, toTip.normalized * length, root.forward * depth);
                return box;
            }

            var capsule = bone.gameObject.AddComponent<CapsuleCollider>();
            float capsuleRadius = Mathf.Max(0.03f, length * entry.RadiusOfLength);

            capsule.radius = capsuleRadius / scale;
            capsule.height = Mathf.Max(length, capsuleRadius * 2.2f) / scale;
            capsule.direction = LongestLocalAxis(bone, toTip);
            capsule.center = bone.InverseTransformPoint(bone.position + toTip * 0.5f);
            return capsule;
        }

        /// <summary>
        /// A box authored along three WORLD directions, expressed as a local size.
        ///
        /// A <c>BoxCollider</c>'s size is on the transform's own axes and cannot be rotated, so the
        /// honest answer for a bone whose axes point somewhere else is the extent of the authored box
        /// projected onto each local axis. It over-estimates on a bone at 45°, which for a torso shell
        /// is the right way to be wrong.
        ///
        /// Each argument is one full EDGE of the authored box in world metres, so the sum of the
        /// absolute projections is a full size and not a half-extent - which is what
        /// <c>BoxCollider.size</c> wants.
        /// </summary>
        private static Vector3 LocalSize(Transform bone, Vector3 x, Vector3 y, Vector3 z)
        {
            var a = bone.InverseTransformVector(x);
            var b = bone.InverseTransformVector(y);
            var c = bone.InverseTransformVector(z);

            return new Vector3(
                Mathf.Abs(a.x) + Mathf.Abs(b.x) + Mathf.Abs(c.x),
                Mathf.Abs(a.y) + Mathf.Abs(b.y) + Mathf.Abs(c.y),
                Mathf.Abs(a.z) + Mathf.Abs(b.z) + Mathf.Abs(c.z));
        }

        /// <summary>Which of the bone's local axes a capsule should run along: 0 = X, 1 = Y, 2 = Z.</summary>
        private static int LongestLocalAxis(Transform bone, Vector3 worldDirection)
        {
            var local = bone.InverseTransformDirection(worldDirection.normalized);
            float x = Mathf.Abs(local.x);
            float y = Mathf.Abs(local.y);
            float z = Mathf.Abs(local.z);

            if (x >= y && x >= z) return 0;
            return y >= z ? 1 : 2;
        }

        // --- joints -----------------------------------------------------------------------------

        /// <summary>
        /// The limits, and the axis each set of limits is about.
        ///
        /// <b>A <c>CharacterJoint</c>'s twist is the only asymmetric freedom it has</b> - low and high
        /// are separate numbers, while both swings are a single symmetric cone. So a knee and an elbow
        /// are built with the HINGE as their twist axis, not the bone's long axis: a knee that may
        /// swing 90° is a knee that bends both ways, and a leg that folds forwards at the shin is the
        /// single most obvious way for a ragdoll to look broken.
        ///
        /// <b>Which way is forwards is derived, not guessed.</b> A positive rotation about the
        /// character's right axis takes the shin from pointing down to pointing backwards, which is
        /// the way a knee goes; the elbows' hinge is the cross of the arm with the character's
        /// forward, which comes out mirrored between left and right on its own - and it has to, since
        /// the two elbows bend in opposite senses about the same world axis.
        ///
        /// <c>enablePreprocessing = false</c> is the second half of the anti-explosion pair (the first
        /// is <see cref="MaxDepenetration"/>): with it on, PhysX may resolve a badly conditioned joint
        /// chain by teleporting a body.
        /// </summary>
        private static void Configure(
            CharacterJoint joint, in Bone entry, Transform bone,
            Dictionary<HumanBodyBones, Transform> bones, Vector3 right, Vector3 forward)
        {
            joint.anchor = Vector3.zero;
            joint.autoConfigureConnectedAnchor = true;
            joint.enablePreprocessing = false;
            joint.enableProjection = true;
            joint.projectionDistance = 0.1f;
            joint.projectionAngle = 20f;

            var along = AlongBone(entry, bone, bones);

            Vector3 twist;
            Vector3 swing;
            float low, high, swing1, swing2;

            switch (entry.Joint)
            {
                case Hinge.Waist:
                    twist = along; swing = right;
                    low = -25f; high = 25f; swing1 = 25f; swing2 = 20f;
                    break;

                case Hinge.Neck:
                    twist = along; swing = right;
                    low = -40f; high = 40f; swing1 = 30f; swing2 = 25f;
                    break;

                case Hinge.Shoulder:
                    twist = along; swing = Vector3.Cross(along, forward).normalized;
                    low = -45f; high = 45f; swing1 = 75f; swing2 = 50f;
                    break;

                case Hinge.Elbow:
                    // The hinge, mirrored per side by the cross product itself.
                    twist = Vector3.Cross(along, forward).normalized;
                    swing = along;
                    low = -5f; high = 100f; swing1 = 8f; swing2 = 8f;
                    break;

                case Hinge.Hip:
                    twist = along; swing = right;
                    low = -20f; high = 20f; swing1 = 60f; swing2 = 35f;
                    break;

                case Hinge.Knee:
                    twist = right;
                    swing = along;
                    low = -5f; high = 100f; swing1 = 8f; swing2 = 8f;
                    break;

                default:
                    twist = along; swing = right;
                    low = -20f; high = 20f; swing1 = 20f; swing2 = 20f;
                    break;
            }

            joint.axis = bone.InverseTransformDirection(twist.normalized);
            joint.swingAxis = bone.InverseTransformDirection(swing.normalized);

            joint.lowTwistLimit = Limit(low);
            joint.highTwistLimit = Limit(high);
            joint.swing1Limit = Limit(swing1);
            joint.swing2Limit = Limit(swing2);
        }

        /// <summary>Which way this bone points, in world space, for the joint axes to be built from.</summary>
        private static Vector3 AlongBone(
            in Bone entry, Transform bone, Dictionary<HumanBodyBones, Transform> bones)
        {
            var tip = bones.TryGetValue(entry.Tip, out var found) ? found : null;
            if (tip == null || tip == bone) return bone.up;

            var direction = tip.position - bone.position;
            return direction.sqrMagnitude < 1e-6f ? bone.up : direction.normalized;
        }

        /// <summary>
        /// One limit, with a contact distance.
        ///
        /// <c>contactDistance</c> is the slack in which the solver starts pushing back BEFORE the
        /// limit is reached. At 0 (the default) a joint is only ever corrected after it has already
        /// been violated, and a limb hitting its stop at speed then rebounds - the buzzing knee.
        /// </summary>
        private static SoftJointLimit Limit(float degrees) => new()
        {
            limit = degrees,
            bounciness = 0f,
            contactDistance = 3f,
        };
    }
}
