using System.Collections.Generic;
using System.IO;
using Newtonsoft.Json;
using UnityEngine;

namespace TheBlock.Core
{
    /// <summary>
    /// The web build's <c>src/config.ts</c>, deserialized.
    ///
    /// The JSON is generated by <c>scripts/export-config.mjs</c> in the game repo (see
    /// <c>tools/export-config.sh</c> here) and lands in <c>Assets/StreamingAssets</c>. It is a raw
    /// dump: every number is still in three.js's right-handed frame. Run positions through
    /// <see cref="Convert"/> before using them — this class does not convert anything, on purpose,
    /// so it stays diffable against the TypeScript.
    ///
    /// Unknown JSON fields are ignored, so this model can stay a subset and grow unit by unit.
    /// </summary>
    public static class TheBlockConfig
    {
        public const string FileName = "theblock-config.json";

        private static Snapshot _cached;

        public static string Path => System.IO.Path.Combine(Application.streamingAssetsPath, FileName);

        /// <summary>Loads and caches the snapshot. Pass <c>true</c> to force a re-read from disk.</summary>
        public static Snapshot Load(bool reload = false)
        {
            if (_cached != null && !reload) return _cached;

            var path = Path;
            if (!File.Exists(path))
            {
                Debug.LogError(
                    $"TheBlockConfig: {path} is missing. Run tools/export-config.sh to generate it.");
                return null;
            }

            var snapshot = JsonConvert.DeserializeObject<Snapshot>(File.ReadAllText(path));
            if (snapshot?.Config == null)
            {
                Debug.LogError($"TheBlockConfig: {path} parsed but has no `config` object.");
                return null;
            }

            _cached = snapshot;
            return _cached;
        }

        /// <summary>The exporter's envelope: provenance fields plus the config itself.</summary>
        public class Snapshot
        {
            [JsonProperty("$generator")] public string Generator;
            [JsonProperty("$source")] public string Source;
            [JsonProperty("$sourceSha256")] public string SourceSha256;
            [JsonProperty("$handedness")] public string Handedness;
            [JsonProperty("config")] public Root Config;
        }

        /// <summary>Mirrors the top level of <c>config.ts</c>. Only the ported sections are declared.</summary>
        public class Root
        {
            public Vec3 Gravity;
            public GroundSpec Ground;
            public CitySpec City;
            public List<DistrictSpec> Districts;
            public PlaceSpec PizzaPlace;
            public PlaceSpec GasStation;
            public PlaceSpec PoliceStation;
            public PlaceSpec SevenEleven;
            public CameraSpec Camera;
            public PlayerSpec Player;
            public VehicleSpec Vehicle;
        }

        /// <summary>A three.js <c>{x, y, z}</c> literal. Still right-handed — convert before use.</summary>
        public struct Vec3
        {
            public float X;
            public float Y;
            public float Z;

            /// <summary>The raw three.js vector, unconverted. Feed it to <see cref="Convert.Pos(Vector3)"/>.</summary>
            public Vector3 Raw => new Vector3(X, Y, Z);
        }

        /// <summary>
        /// The flat plate every district sits on — the web build's safety floor, and what stops
        /// anything that leaves the city plate falling forever. Square and centred on the origin.
        /// </summary>
        public class GroundSpec
        {
            /// <summary>Edge length in metres.</summary>
            public float Size = 1400f;

            /// <summary>Packed <c>0xRRGGBB</c>. See <see cref="ColorFromHex"/>.</summary>
            public int Color;

            /// <summary>Height. Slightly below zero so district ground wins wherever they overlap.</summary>
            public float Y = -0.05f;
        }

        /// <summary>Downtown. Unlike the other districts it carries the facade tint list.</summary>
        public class CitySpec
        {
            public string Url;
            public string Name;
            public float Scale = 1f;
            public Vec3 Position;

            /// <summary>Material names the web build recolours at load. Unity binds a material asset instead.</summary>
            public List<string> FacadeMaterials;

            /// <summary>Substrings that mark a mesh as foliage: rendered, never collided with.</summary>
            public List<string> NoCollidePatterns;
        }

        /// <summary>An outlying district GLB, offset from downtown.</summary>
        public class DistrictSpec
        {
            public string Url;
            public string Name;
            public float Scale = 1f;
            public Vec3 Position;

            /// <summary>Materials whose meshes are hidden outright — the baked-in parked cars.</summary>
            public List<string> HideMaterials;

            public List<string> NoCollidePatterns;
        }

        /// <summary>A placed landmark: the pizzeria, gas station, police station, 7-Eleven.</summary>
        public class PlaceSpec
        {
            public string Url;
            public string Name;
            public float Scale = 1f;
            public Vec3 Position;

            /// <summary>Yaw in radians, right-handed. Use <see cref="Convert.RotFromRadians"/>.</summary>
            public float Yaw;

            public List<string> HideNodes;
            public List<string> NoCollideNodes;

            /// <summary>When set, only meshes topping out at or below this height get a collider.</summary>
            public float? CollideMaxY;
        }

        /// <summary>
        /// Lens settings, plus the VEHICLE chase boom — the on-foot boom lives on
        /// <see cref="PlayerCameraSpec"/>. That split is the web build's, kept so the two files stay
        /// diffable: <c>config.camera.localOffset</c> is what <c>vehicle.ts</c>'s <c>follow()</c> reads.
        /// </summary>
        public class CameraSpec
        {
            public float Fov = 75f;
            public float Near = 0.1f;
            public float Far = 320f;

            /// <summary>
            /// The chase boom in the VEHICLE's own frame. Run it through
            /// <see cref="Convert.ModelOffset"/>, never <see cref="Convert.Pos"/>.
            /// </summary>
            public Vec3 LocalOffset;

            public float LookYOffset = 0.5f;

            /// <summary>Fraction of the remaining distance closed per frame at 60 fps.</summary>
            public float FollowLerp = 0.12f;
        }

        /// <summary>
        /// Vehicles. Only the fields that survive the engine change are declared.
        ///
        /// Most of <c>config.vehicle</c> is deliberately ABSENT: <c>accel</c>, <c>brakeDecel</c>,
        /// <c>friction</c>, <c>steerRatio</c>, <c>wheelReturn</c>, <c>colliderHeight</c>,
        /// <c>colliderBottomGap</c>, <c>blockedRatio</c>, <c>blockBleedMinSpeed</c>,
        /// <c>maxClimbRate</c> and <c>characterOffset</c> all describe a KINEMATIC car — a scalar
        /// speed pushed through a Rapier character controller with a ground ray under it. Unity
        /// drives a Rigidbody on four WheelColliders, where those quantities are outputs of mass,
        /// suspension and tyre friction rather than inputs. Declaring them would invite someone to
        /// wire them up, and they would be wrong (CLAUDE.md port rule 2). Their Unity replacements
        /// are serialized on <c>CarController</c>, where they can be tuned against the real thing.
        ///
        /// What is left is gameplay: how fast the car may go, how far the wheels turn, how close you
        /// must stand to get in.
        /// </summary>
        public class VehicleSpec
        {
            /// <summary>Forward speed cap in m/s (20 → ~72 km/h).</summary>
            public float MaxSpeed = 20f;

            public float ReverseMaxSpeed = 7f;

            /// <summary>Steering lock in RADIANS (0.6 → ~34°). Degrees at the WheelCollider.</summary>
            public float MaxWheelAngle = 0.6f;

            /// <summary>How near the player must be to enter. U9's number, parked here with its family.</summary>
            public float EnterRadius = 4.5f;

            public List<CarSpec> Cars;
        }

        /// <summary>One drivable car. The web build lists 16; U8 builds the Mustang.</summary>
        public class CarSpec
        {
            public string Name;
            public string ModelUrl;
            public float ModelScale = 1f;

            /// <summary>
            /// Radians, right-handed, rotating the model so its front faces three.js's <c>-Z</c>.
            /// Compose it with <see cref="Convert.ModelFacing"/> to reach Unity's <c>+Z</c>.
            /// </summary>
            public float ModelYaw;

            /// <summary>
            /// Packed <c>0xRRGGBB</c>, applied to the <c>CarPrimaryColor</c> material slot. Null
            /// keeps the model's own paint. These are sRGB bytes — see
            /// <see cref="ColorFromHex"/> for why that matters.
            /// </summary>
            public int? BodyColor;

            /// <summary>Ground-plane spawn. There is no Y: the car settles onto whatever is under it.</summary>
            public SpawnSpec Spawn;

            /// <summary>Initial heading in radians, right-handed. Absent → 0.</summary>
            public float? SpawnYaw;

            /// <summary>Surface height the web build's ground ray expected. Unity's suspension finds it instead.</summary>
            public float RoadSurfaceY;

            public DoorSpec Door;
        }

        /// <summary>A car spawn: X and Z only, in three.js's frame.</summary>
        public struct SpawnSpec
        {
            public float X;
            public float Z;

            /// <summary>Unconverted, at <c>y = 0</c>. Feed it to <see cref="Convert.Pos(Vector3)"/>.</summary>
            public Vector3 Raw => new Vector3(X, 0f, Z);
        }

        /// <summary>The single hinged driver door. U9 animates it; U8 only carries it across.</summary>
        public class DoorSpec
        {
            public string JointName;

            /// <summary>Hinge axis in the MODEL's frame: "x", "y" or "z".</summary>
            public string Axis;

            /// <summary>Open angle in radians.</summary>
            public float OpenAngle;

            public float LerpRate = 8f;
        }

        /// <summary>
        /// A packed <c>0xRRGGBB</c> from config as a Unity colour.
        ///
        /// Built with <c>new Color(r, g, b)</c> and NOT <c>.linear</c>: those bytes are sRGB, and a
        /// URP material's <c>_BaseColor</c> takes sRGB. Converting to linear first darkens the paint
        /// to near-black — the same trap glTFast's <c>baseColorFactor</c> sets (see the
        /// <c>gltfast-basecolorfactor-gamma</c> memory).
        /// </summary>
        public static Color ColorFromHex(int packed) => new Color(
            ((packed >> 16) & 0xFF) / 255f,
            ((packed >> 8) & 0xFF) / 255f,
            (packed & 0xFF) / 255f);

        /// <summary>
        /// The on-foot player. Speeds and stamina are gameplay tuning and port straight across;
        /// the collider dimensions describe a body, not a physics response, so they port too.
        /// </summary>
        public class PlayerSpec
        {
            public float Scale = 1f;

            /// <summary>The parking lot. Unusable until that district is ingested — see PORT-STATUS.</summary>
            public Vec3 Spawn;

            public ColliderSpec Collider;

            /// <summary>Skin width: how far the controller is allowed to sink into geometry.</summary>
            public float CharacterOffset = 0.05f;

            public MovementSpec Movement;
            public StaminaSpec Stamina;
            public float AnimCrossfadeSec = 0.18f;

            /// <summary>Radians per second.</summary>
            public float TurnSpeed = 6f;

            public float JumpForce = 5f;

            /// <summary>Descent speed past which the face-down free-fall pose takes over.</summary>
            public float FallSpeedThreshold = 8f;

            public PlayerCameraSpec Camera;
        }

        /// <summary>Capsule: total height is <c>2 * (HalfHeight + Radius)</c>, origin at the feet.</summary>
        public class ColliderSpec
        {
            public float Radius = 0.3f;
            public float HalfHeight = 0.6f;
        }

        /// <summary>Three-tier gait in m/s: no modifier walks, Alt jogs, Shift sprints.</summary>
        public class MovementSpec
        {
            public float WalkSpeed = 2f;
            public float JogSpeed = 4.5f;
            public float SprintSpeed = 7f;
        }

        /// <summary>Sprint budget. Empty forces a walk until it climbs back to <see cref="ResumeThreshold"/>.</summary>
        public class StaminaSpec
        {
            public float Max = 100f;
            public float DrainPerSec = 25f;
            public float RegenPerSec = 18f;
            public float JogRegenPerSec = 6f;
            public float ResumeThreshold = 20f;
        }

        /// <summary>
        /// The third-person boom, in the player's LOCAL frame. Run it through
        /// <see cref="Convert.ModelOffset"/>, not <see cref="Convert.Pos"/> — three.js faces -Z.
        /// </summary>
        public class PlayerCameraSpec
        {
            public Vec3 Offset;
            public float LookYOffset = 1.8f;

            /// <summary>Fraction of the remaining distance closed per frame at 60 fps.</summary>
            public float FollowLerp = 0.25f;
        }
    }
}
