using System.Collections.Generic;
using System.IO;
using Newtonsoft.Json;
using UnityEngine;

namespace TheBlock.Core
{
    /// <summary>
    /// The web build's <c>src/config.ts</c>, deserialized.
    ///
    /// The JSON is generated by <c>scripts/export-config.mjs</c> in the game repo (see
    /// <c>tools/export-config.sh</c> here) and lands in <c>Assets/StreamingAssets</c>. It is a raw
    /// dump: every number is still in three.js's right-handed frame. Run positions through
    /// <see cref="Convert"/> before using them — this class does not convert anything, on purpose,
    /// so it stays diffable against the TypeScript.
    ///
    /// Unknown JSON fields are ignored, so this model can stay a subset and grow unit by unit.
    /// </summary>
    public static class TheBlockConfig
    {
        public const string FileName = "theblock-config.json";

        private static Snapshot _cached;

        public static string Path => System.IO.Path.Combine(Application.streamingAssetsPath, FileName);

        /// <summary>Loads and caches the snapshot. Pass <c>true</c> to force a re-read from disk.</summary>
        public static Snapshot Load(bool reload = false)
        {
            if (_cached != null && !reload) return _cached;

            var path = Path;
            if (!File.Exists(path))
            {
                Debug.LogError(
                    $"TheBlockConfig: {path} is missing. Run tools/export-config.sh to generate it.");
                return null;
            }

            var snapshot = JsonConvert.DeserializeObject<Snapshot>(File.ReadAllText(path));
            if (snapshot?.Config == null)
            {
                Debug.LogError($"TheBlockConfig: {path} parsed but has no `config` object.");
                return null;
            }

            _cached = snapshot;
            return _cached;
        }

        /// <summary>The exporter's envelope: provenance fields plus the config itself.</summary>
        public class Snapshot
        {
            [JsonProperty("$generator")] public string Generator;
            [JsonProperty("$source")] public string Source;
            [JsonProperty("$sourceSha256")] public string SourceSha256;
            [JsonProperty("$handedness")] public string Handedness;
            [JsonProperty("config")] public Root Config;
        }

        /// <summary>Mirrors the top level of <c>config.ts</c>. Only the ported sections are declared.</summary>
        public class Root
        {
            public Vec3 Gravity;
            public GroundSpec Ground;
            public RoadsSpec Roads;
            public SeaSpec Sea;
            public MapSpec Map;
            public CitySpec City;
            public List<DistrictSpec> Districts;
            public PlaceSpec PizzaPlace;
            public PlaceSpec GasStation;
            public PlaceSpec PoliceStation;
            public PlaceSpec SevenEleven;
            public LotCarsSpec LotCars;
            public InteriorSpec Interior;
            public CameraSpec Camera;
            public PlayerSpec Player;
            public VehicleSpec Vehicle;

            /// <summary>
            /// The street haze. Its colour is identical to <see cref="Background"/> in
            /// <c>config.ts</c>, and that is the whole mechanism — see <see cref="World.Atmosphere"/>.
            /// </summary>
            public FogSpec Fog;

            /// <summary>The sky colour geometry fades into. Equal to <c>fog.color</c> by design.</summary>
            public int Background;
        }

        /// <summary>A three.js <c>{x, y, z}</c> literal. Still right-handed — convert before use.</summary>
        public struct Vec3
        {
            public float X;
            public float Y;
            public float Z;

            /// <summary>The raw three.js vector, unconverted. Feed it to <see cref="Convert.Pos(Vector3)"/>.</summary>
            public Vector3 Raw => new Vector3(X, Y, Z);
        }

        /// <summary>
        /// The flat plate every district sits on — the web build's safety floor, and what stops
        /// anything that leaves the city plate falling forever. Square and centred on the origin.
        /// </summary>
        public class GroundSpec
        {
            /// <summary>Edge length in metres.</summary>
            public float Size = 1400f;

            /// <summary>Packed <c>0xRRGGBB</c>. See <see cref="ColorFromHex"/>.</summary>
            public int Color;

            /// <summary>Height. Slightly below zero so district ground wins wherever they overlap.</summary>
            public float Y = -0.05f;
        }

        /// <summary>
        /// The road network: a list of centreline polylines, still right-handed.
        ///
        /// The web build cloned one 8 m-wide tile per A→B segment because that is all three.js gave
        /// it. Unity generates a continuous ribbon along a spline through the same points, so a bend
        /// is a curve rather than two quads overlapping at the corner. The polylines themselves are
        /// untouched — U17's traffic graph reads the same numbers.
        /// </summary>
        public class RoadsSpec
        {
            /// <summary>The web build's tile GLB. Unity generates its mesh instead; kept for provenance.</summary>
            public string Url;

            /// <summary>Surface height. Just above the ground plate, flush with district pavement.</summary>
            public float Y = 0.02f;

            /// <summary>Centrelines. Each point carries x and z only — y is the section's.</summary>
            public List<List<Vec3>> Paths;
        }

        /// <summary>
        /// The Mediterranean on the world's west edge — which is Unity's EAST, at <c>+x</c>, because
        /// <see cref="Convert"/> negates X. <c>ShoreX -430</c> is Unity <c>x +430</c>, and the water
        /// runs outward from there to <c>+x</c>.
        /// </summary>
        public class SeaSpec
        {
            /// <summary>Waterline X, right-handed. Convert it.</summary>
            public float ShoreX = -430f;

            /// <summary>Sea level in world Y. The city ground is 0 too.</summary>
            public float Level;

            /// <summary>Water plane extent perpendicular to the shore.</summary>
            public float Width = 2400f;

            /// <summary>Water and beach extent ALONG the shore (Z).</summary>
            public float Length = 600f;

            /// <summary>Centre of that Z span. Z does not flip.</summary>
            public float CenterZ;

            public SeaSurfaceSpec Surface;
            public BeachSpec Beach;
            public SeaWallSpec Wall;
        }

        /// <summary>Water shader tuning — every number is a material property on <c>TheBlock/Water</c>.</summary>
        public class SeaSurfaceSpec
        {
            public string NormalMap;
            public int DeepColor;
            public int ShallowColor;
            public int SkyColor;
            public float FresnelCeil = 0.6f;
            public int FoamColor;
            public float FoamStrength = 0.32f;
            public float RippleStrength = 0.35f;
            public float SpecPower = 180f;

            /// <summary>Water this deep gets full swell height; shallower fades to flat at the waterline.</summary>
            public float SwellFadeDepth = 1.5f;

            /// <summary>Plane subdivisions. The swells are a vertex displacement, so this is the shape.</summary>
            public int SegX = 128;
            public int SegZ = 32;

            public List<WaveSpec> Waves;
        }

        /// <summary>One directional sine swell.</summary>
        public class WaveSpec
        {
            public float DirX;
            public float DirZ;
            public float Amplitude;
            public float Wavelength;
            public float Speed;
        }

        /// <summary>
        /// The sand: flat and dry landward of the shore, ramping to <see cref="DeepY"/> over
        /// <see cref="WadeRun"/> metres seaward of it. This is a real walkable floor, not decoration.
        /// </summary>
        public class BeachSpec
        {
            public int Color;
            public float Roughness = 0.9f;

            /// <summary>Dry sand landward of the shore, bridging to the city ground.</summary>
            public float DryWidth = 25f;

            /// <summary>Distance over which the seabed drops from the waterline to <see cref="DeepY"/>.</summary>
            public float WadeRun = 35f;

            public float DeepY = -3f;
            public int SegX = 96;
            public int SegZ = 8;
            public BeachLookSpec Look;
        }

        /// <summary>Sand shading — procedural, no textures. Ported to <c>TheBlock/Beach</c>.</summary>
        public class BeachLookSpec
        {
            public int DryColor;
            public int DryShadowColor;
            public int WetColor;
            public float GrainScale = 6f;
            public float GrainStrength = 0.08f;
            public float BlotchScale = 26f;
            public float BlotchStrength = 0.55f;
            public float WetBandDry = 0.6f;
            public float WetBandSea = 0.5f;
            public float DryRoughness = 0.95f;
            public float WetRoughness = 0.45f;
        }

        /// <summary>The invisible boundary at the waterline. Collider only, never drawn.</summary>
        public class SeaWallSpec
        {
            public float Height = 8f;
            public float Thickness = 3f;
        }

        /// <summary>
        /// Minimap + full map tuning.
        ///
        /// Two of <c>config.map</c>'s fields are deliberately ABSENT. <c>bakeRes</c> sized a
        /// once-per-boot top-down render that three.js read back into a canvas, because a second
        /// live camera every frame was not affordable there; Unity renders the map camera into a
        /// RenderTexture directly, so there is no bake to size. <c>districtFill</c> filled the
        /// district boxes only when that bake was missing — with a live render there is always
        /// something underneath, so only the stroke is used.
        /// </summary>
        public class MapSpec
        {
            /// <summary>Half-extent in metres shown around the player on the minimap.</summary>
            public float MinimapRangeM = 150f;

            /// <summary>Inset, in panel pixels, when fitting the whole world into the full map.</summary>
            public float Padding = 18f;

            /// <summary>How far past the shore the full map frames, so the coast is on-canvas.</summary>
            public float SeaBandM = 140f;

            /// <summary>CSS colour strings — see <see cref="ColorFromCss"/>.</summary>
            public string DistrictStroke;

            public string LabelColor;
            public string LabelText;
            public string LabelPill;
            public string Player;

            /// <summary>Keyed by the POI kind: <c>pizza</c>, <c>vehicle</c>, <c>spawn</c>, <c>marker</c>.</summary>
            public Dictionary<string, string> PoiColors;
        }

        /// <summary>
        /// A CSS colour string from config — <c>#rrggbb</c> or <c>rgba(r, g, b, a)</c> — as a Unity
        /// colour. The map section stores its palette as CSS because the web build fed it straight to
        /// a 2D canvas; nothing else in config.ts does.
        ///
        /// Built without <c>.linear</c> for the same reason as <see cref="ColorFromHex"/>: these are
        /// sRGB bytes, and UI Toolkit's painter takes sRGB.
        /// </summary>
        public static Color ColorFromCss(string css, Color fallback)
        {
            if (string.IsNullOrWhiteSpace(css)) return fallback;
            var s = css.Trim();

            if (s[0] == '#')
                return ColorUtility.TryParseHtmlString(s, out var parsed) ? parsed : fallback;

            var open = s.IndexOf('(');
            var close = s.IndexOf(')');
            if (open < 0 || close < open) return fallback;

            var parts = s.Substring(open + 1, close - open - 1).Split(',');
            if (parts.Length < 3) return fallback;
            if (!float.TryParse(parts[0], System.Globalization.NumberStyles.Float,
                    System.Globalization.CultureInfo.InvariantCulture, out var r) ||
                !float.TryParse(parts[1], System.Globalization.NumberStyles.Float,
                    System.Globalization.CultureInfo.InvariantCulture, out var g) ||
                !float.TryParse(parts[2], System.Globalization.NumberStyles.Float,
                    System.Globalization.CultureInfo.InvariantCulture, out var b))
                return fallback;

            var a = 1f;
            if (parts.Length >= 4)
                float.TryParse(parts[3], System.Globalization.NumberStyles.Float,
                    System.Globalization.CultureInfo.InvariantCulture, out a);

            return new Color(r / 255f, g / 255f, b / 255f, a);
        }

        /// <summary>Downtown. Unlike the other districts it carries the facade tint list.</summary>
        public class CitySpec
        {
            public string Url;
            public string Name;
            public float Scale = 1f;
            public Vec3 Position;

            /// <summary>Material names the web build recolours at load. Unity binds a material asset instead.</summary>
            public List<string> FacadeMaterials;

            /// <summary>Substrings that mark a mesh as foliage: rendered, never collided with.</summary>
            public List<string> NoCollidePatterns;
        }

        /// <summary>An outlying district GLB, offset from downtown.</summary>
        public class DistrictSpec
        {
            public string Url;
            public string Name;
            public float Scale = 1f;
            public Vec3 Position;

            /// <summary>Materials whose meshes are hidden outright — the baked-in parked cars.</summary>
            public List<string> HideMaterials;

            public List<string> NoCollidePatterns;
        }

        /// <summary>A placed landmark: the pizzeria, gas station, police station, 7-Eleven.</summary>
        public class PlaceSpec
        {
            public string Url;
            public string Name;
            public float Scale = 1f;
            public Vec3 Position;

            /// <summary>Yaw in radians, right-handed. Use <see cref="Convert.RotFromRadians"/>.</summary>
            public float Yaw;

            public List<string> HideNodes;
            public List<string> NoCollideNodes;

            /// <summary>When set, only meshes topping out at or below this height get a collider.</summary>
            public float? CollideMaxY;
        }

        /// <summary>
        /// The parked-car filler for the big lot. Everything here is authored in the web build's
        /// right-handed frame, including <see cref="LotBounds"/> and <see cref="KeepClear"/>, so the
        /// rectangles' min/max in X swap when converted.
        /// </summary>
        public class LotCarsSpec
        {
            public List<LotCarModelSpec> Models;
            [JsonProperty("bounds")] public RectSpec LotBounds;

            /// <summary>Stall spacing along the row (X), metres.</summary>
            public float StallPitchX = 3.4f;

            /// <summary>Depth of one row; two rows sit back to back, then an aisle.</summary>
            public float RowDepth = 6f;

            public float AisleGap = 7f;

            /// <summary>Fraction of stalls that get a car, rolled per stall.</summary>
            public float Occupancy = 0.22f;

            /// <summary>Lot surface height the wheels rest on.</summary>
            public float Y = 0.1f;

            /// <summary>Seed for the layout PRNG — the same lot every build.</summary>
            public int Seed = 1337;

            /// <summary>Rectangles left empty: the drivable cars' and the player's spawn area.</summary>
            public List<RectSpec> KeepClear;

            /// <summary>Weighted paint mix, mostly white/black/grey.</summary>
            public List<PaintSpec> Palette;
        }

        public class LotCarModelSpec
        {
            public string Url;
            public string Name;
            public float Scale = 1f;

            /// <summary>The model's own facing correction, radians. Right-handed.</summary>
            public float ModelYaw;

            /// <summary>When present, this model ignores the global palette and picks from here.</summary>
            public List<int> Palette;
        }

        /// <summary>An axis-aligned XZ rectangle in the web build's frame.</summary>
        public class RectSpec
        {
            public float MinX;
            public float MaxX;
            public float MinZ;
            public float MaxZ;
        }

        public class PaintSpec
        {
            public int Hex;
            public float Weight = 1f;
        }

        /// <summary>
        /// The pizzeria's interior "cell" — a room parked far from the city so its geometry and its
        /// lights never touch the street. Entering teleports the player into it.
        /// </summary>
        public class InteriorSpec
        {
            public string AssetUrl;

            /// <summary>Where the room sits. Everything below is stated relative to it.</summary>
            public Vec3 Offset;

            public InteriorSpawnSpec Spawn;
            public PadSpec ExitPad;

            /// <summary>The circle on the street that takes you in. World coords, not offset-relative.</summary>
            public PadSpec StreetDoorTrigger;

            public InteriorPaletteSpec Palette;
            public List<InteriorLightSpec> Lights;
        }

        public class InteriorSpawnSpec
        {
            public float X;
            public float Y;
            public float Z;

            /// <summary>Yaw in radians, right-handed.</summary>
            public float Yaw;

            /// <summary>The raw three.js vector, unconverted.</summary>
            public Vector3 Raw => new Vector3(X, Y, Z);
        }

        /// <summary>A circle on the floor. <c>y</c> is absent in the config; only XZ is tested.</summary>
        public class PadSpec
        {
            public float X;
            public float Z;
            public float Radius = 1f;

            /// <summary>The raw three.js position, unconverted, at <c>y = 0</c>.</summary>
            public Vector3 Raw => new Vector3(X, 0f, Z);
        }

        public class InteriorPaletteSpec
        {
            public int Background;
            public FogSpec Fog;
            public float SunIntensity = 0.12f;
            public AmbientSpec Ambient;
        }

        public class FogSpec
        {
            public int Color;
            public float Near = 5f;
            public float Far = 26f;
        }

        public class AmbientSpec
        {
            public int Color;
            public float Intensity = 0.45f;
        }

        public class InteriorLightSpec
        {
            public float X;
            public float Y;
            public float Z;
            public int Color;

            /// <summary>three.js point-light intensity — NOT a Unity value; see the interior builder.</summary>
            public float Intensity;

            /// <summary>Range in metres.</summary>
            public float Distance = 12f;

            /// <summary>The raw three.js vector, unconverted.</summary>
            public Vector3 Raw => new Vector3(X, Y, Z);
        }

        /// <summary>
        /// Lens settings, plus the VEHICLE chase boom — the on-foot boom lives on
        /// <see cref="PlayerCameraSpec"/>. That split is the web build's, kept so the two files stay
        /// diffable: <c>config.camera.localOffset</c> is what <c>vehicle.ts</c>'s <c>follow()</c> reads.
        /// </summary>
        public class CameraSpec
        {
            public float Fov = 75f;
            public float Near = 0.1f;
            public float Far = 320f;

            /// <summary>
            /// The chase boom in the VEHICLE's own frame. Run it through
            /// <see cref="Convert.ModelOffset"/>, never <see cref="Convert.Pos"/>.
            /// </summary>
            public Vec3 LocalOffset;

            public float LookYOffset = 0.5f;

            /// <summary>Fraction of the remaining distance closed per frame at 60 fps.</summary>
            public float FollowLerp = 0.12f;
        }

        /// <summary>
        /// Vehicles. Only the fields that survive the engine change are declared.
        ///
        /// Most of <c>config.vehicle</c> is deliberately ABSENT: <c>accel</c>, <c>brakeDecel</c>,
        /// <c>friction</c>, <c>steerRatio</c>, <c>wheelReturn</c>, <c>colliderHeight</c>,
        /// <c>colliderBottomGap</c>, <c>blockedRatio</c>, <c>blockBleedMinSpeed</c>,
        /// <c>maxClimbRate</c> and <c>characterOffset</c> all describe a KINEMATIC car — a scalar
        /// speed pushed through a Rapier character controller with a ground ray under it. Unity
        /// drives a Rigidbody on four WheelColliders, where those quantities are outputs of mass,
        /// suspension and tyre friction rather than inputs. Declaring them would invite someone to
        /// wire them up, and they would be wrong (CLAUDE.md port rule 2). Their Unity replacements
        /// are serialized on <c>CarController</c>, where they can be tuned against the real thing.
        ///
        /// What is left is gameplay: how fast the car may go, how far the wheels turn, how close you
        /// must stand to get in.
        /// </summary>
        public class VehicleSpec
        {
            /// <summary>Forward speed cap in m/s (20 → ~72 km/h).</summary>
            public float MaxSpeed = 20f;

            public float ReverseMaxSpeed = 7f;

            /// <summary>Steering lock in RADIANS (0.6 → ~34°). Degrees at the WheelCollider.</summary>
            public float MaxWheelAngle = 0.6f;

            /// <summary>How near the player must be to enter, in metres, measured on the ground plane.</summary>
            public float EnterRadius = 4.5f;

            /// <summary>
            /// Quick-enter timings, in seconds. These are the fallback path: the door swings for
            /// <see cref="EnterDoorOpenTime"/>, the driver appears, and
            /// <see cref="EnterDoorCloseDelay"/> later it shuts and the car is drivable. A car with
            /// a <see cref="DriverSpec"/> seat block uses its entry CLIP instead and ignores both —
            /// the same split the web build makes between tuned and untuned cars.
            /// </summary>
            public float EnterDoorOpenTime = 0.55f;

            public float EnterDoorCloseDelay = 0.5f;

            /// <summary>How long the door stays open behind you on the way out, in seconds.</summary>
            public float ExitDoorCloseTime = 0.6f;

            /// <summary>How far beside the car the driver is set down, in metres.</summary>
            public float ExitSideOffset = 1.8f;

            // --- Arcade driving model (not in cars.[] but applies to every car and the motorcycle) ---
            public float Accel = 14f;
            public float BrakeDecel = 30f;
            public float Friction = 7f;
            public float SteerRatio = 0.25f;
            public float WheelReturn = 8f;

            public DriverSpec Driver;

            public List<CarSpec> Cars;

            public MotorcycleSpec Motorcycle;
        }

        /// <summary>Pizza-delivery motorcycle (Mission 1). Door-less; rider uses the shared Driving animation.</summary>
        public class MotorcycleSpec
        {
            public string ModelUrl;
            public float ModelScale = 0.66f;
            public float ModelYaw;
            public SpawnSpec Spawn;
            public float RoadSurfaceY;
            public float GroundClearance = 0.12f;

            /// <summary>Rider placement in holder-local space.</summary>
            public RiderSpec Rider;
        }

        /// <summary>Rider placement on a two-wheeler (motorcycle, jetski).</summary>
        public class RiderSpec
        {
            public float Scale = 1f;
            public float Yaw;
            public PositionSpec Seat;
        }

        /// <summary>A 3D position: X, Y, Z.</summary>
        public class PositionSpec
        {
            public float X;
            public float Y;
            public float Z;

            public Vector3 Raw => new Vector3(X, Y, Z);
        }

        /// <summary>
        /// The seated driver: where the entry animation starts, per car model, and when the door
        /// swings during it.
        ///
        /// The seat block is NOT the seat cushion. It is where the entry clip's own origin goes —
        /// the driver standing beside the door at road level — and the clip's baked hip travel
        /// carries him from there into the car. That is why the Mustang's <c>x</c> is 2.31 m, which
        /// would be outside a 2 m-wide car if it meant the cushion.
        /// </summary>
        public class DriverSpec
        {
            /// <summary>Entry-clip progress in [0,1] at which the door starts opening.</summary>
            public float DoorOpenAt = 0.25f;

            /// <summary>Entry-clip progress at which it starts shutting again.</summary>
            public float DoorCloseAt = 0.7f;

            /// <summary>Keyed by <c>modelUrl</c> — a car with no entry here gets the quick enter.</summary>
            public Dictionary<string, SeatSpec> Seats;
        }

        /// <summary>
        /// One car model's driver anchor, in the car's own local frame, measured from the BODY
        /// CENTRE — the web build recentres each car inside a holder, so that is what its numbers
        /// are relative to. Unity's prefab root sits on the tyre contact patch instead, so
        /// <c>CarBuilder</c> adds the measured body centre back before placing the anchor.
        /// </summary>
        public class SeatSpec
        {
            public float X;
            public float Y;
            public float Z;

            /// <summary>Radians, right-handed. Use <see cref="Convert.RotFromRadians"/>.</summary>
            public float Yaw;

            /// <summary>Uniform scale on the driver, so a body that sits a touch large is trimmed.</summary>
            public float Scale = 1f;

            /// <summary>Unconverted. Feed it to <see cref="Convert.ModelOffset"/>, never <see cref="Convert.Pos"/>.</summary>
            public Vector3 Raw => new Vector3(X, Y, Z);
        }

        /// <summary>One drivable car. The web build lists 16; U8 builds the Mustang.</summary>
        public class CarSpec
        {
            public string Name;
            public string ModelUrl;
            public float ModelScale = 1f;

            /// <summary>
            /// Radians, right-handed, rotating the model so its front faces three.js's <c>-Z</c>.
            /// Compose it with <see cref="Convert.ModelFacing"/> to reach Unity's <c>+Z</c>.
            /// </summary>
            public float ModelYaw;

            /// <summary>
            /// Packed <c>0xRRGGBB</c>, applied to the <c>CarPrimaryColor</c> material slot. Null
            /// keeps the model's own paint. These are sRGB bytes — see
            /// <see cref="ColorFromHex"/> for why that matters.
            /// </summary>
            public int? BodyColor;

            /// <summary>Ground-plane spawn. There is no Y: the car settles onto whatever is under it.</summary>
            public SpawnSpec Spawn;

            /// <summary>Initial heading in radians, right-handed. Absent → 0.</summary>
            public float? SpawnYaw;

            /// <summary>Surface height the web build's ground ray expected. Unity's suspension finds it instead.</summary>
            public float RoadSurfaceY;

            public DoorSpec Door;
        }

        /// <summary>A car spawn: X and Z only, in three.js's frame.</summary>
        public struct SpawnSpec
        {
            public float X;
            public float Z;

            /// <summary>Unconverted, at <c>y = 0</c>. Feed it to <see cref="Convert.Pos(Vector3)"/>.</summary>
            public Vector3 Raw => new Vector3(X, 0f, Z);
        }

        /// <summary>
        /// The single hinged driver door, as a bone in the car's own armature. The GLB puts that
        /// joint at the real hinge, so rotating the bone is enough and the skinned mesh follows —
        /// no pivot wrapper, the same trick <c>CarWheel</c> uses.
        /// </summary>
        public class DoorSpec
        {
            public string JointName;

            /// <summary>Hinge axis in the BONE's own local frame: "x", "y" or "z".</summary>
            public string Axis;

            /// <summary>Open angle in radians, right-handed. See <see cref="Convert.ModelAxis"/>.</summary>
            public float OpenAngle;

            /// <summary>Exponential smoothing rate; higher is snappier. Frame-rate independent.</summary>
            public float LerpRate = 8f;
        }

        /// <summary>
        /// A packed <c>0xRRGGBB</c> from config as a Unity colour.
        ///
        /// Built with <c>new Color(r, g, b)</c> and NOT <c>.linear</c>: those bytes are sRGB, and a
        /// URP material's <c>_BaseColor</c> takes sRGB. Converting to linear first darkens the paint
        /// to near-black — the same trap glTFast's <c>baseColorFactor</c> sets (see the
        /// <c>gltfast-basecolorfactor-gamma</c> memory).
        /// </summary>
        public static Color ColorFromHex(int packed) => new Color(
            ((packed >> 16) & 0xFF) / 255f,
            ((packed >> 8) & 0xFF) / 255f,
            (packed & 0xFF) / 255f);

        /// <summary>
        /// The on-foot player. Speeds and stamina are gameplay tuning and port straight across;
        /// the collider dimensions describe a body, not a physics response, so they port too.
        /// </summary>
        public class PlayerSpec
        {
            public float Scale = 1f;

            /// <summary>The parking lot. Unusable until that district is ingested — see PORT-STATUS.</summary>
            public Vec3 Spawn;

            public ColliderSpec Collider;

            /// <summary>Skin width: how far the controller is allowed to sink into geometry.</summary>
            public float CharacterOffset = 0.05f;

            public MovementSpec Movement;
            public StaminaSpec Stamina;
            public float AnimCrossfadeSec = 0.18f;

            /// <summary>Radians per second.</summary>
            public float TurnSpeed = 6f;

            public float JumpForce = 5f;

            /// <summary>Descent speed past which the face-down free-fall pose takes over.</summary>
            public float FallSpeedThreshold = 8f;

            public PlayerCameraSpec Camera;
        }

        /// <summary>Capsule: total height is <c>2 * (HalfHeight + Radius)</c>, origin at the feet.</summary>
        public class ColliderSpec
        {
            public float Radius = 0.3f;
            public float HalfHeight = 0.6f;
        }

        /// <summary>Three-tier gait in m/s: no modifier walks, Alt jogs, Shift sprints.</summary>
        public class MovementSpec
        {
            public float WalkSpeed = 2f;
            public float JogSpeed = 4.5f;
            public float SprintSpeed = 7f;
        }

        /// <summary>Sprint budget. Empty forces a walk until it climbs back to <see cref="ResumeThreshold"/>.</summary>
        public class StaminaSpec
        {
            public float Max = 100f;
            public float DrainPerSec = 25f;
            public float RegenPerSec = 18f;
            public float JogRegenPerSec = 6f;
            public float ResumeThreshold = 20f;
        }

        /// <summary>
        /// The third-person boom, in the player's LOCAL frame. Run it through
        /// <see cref="Convert.ModelOffset"/>, not <see cref="Convert.Pos"/> — three.js faces -Z.
        /// </summary>
        public class PlayerCameraSpec
        {
            public Vec3 Offset;
            public float LookYOffset = 1.8f;

            /// <summary>Fraction of the remaining distance closed per frame at 60 fps.</summary>
            public float FollowLerp = 0.25f;
        }
    }
}
