using System.Collections.Generic;
using System.IO;
using Newtonsoft.Json;
using UnityEngine;

namespace TheBlock.Core
{
    /// <summary>
    /// The web build's <c>src/config.ts</c>, deserialized.
    ///
    /// The JSON is generated by <c>scripts/export-config.mjs</c> in the game repo (see
    /// <c>tools/export-config.sh</c> here) and lands in <c>Assets/StreamingAssets</c>. It is a raw
    /// dump: every number is still in three.js's right-handed frame. Run positions through
    /// <see cref="Convert"/> before using them — this class does not convert anything, on purpose,
    /// so it stays diffable against the TypeScript.
    ///
    /// Unknown JSON fields are ignored, so this model can stay a subset and grow unit by unit.
    /// </summary>
    public static class TheBlockConfig
    {
        public const string FileName = "theblock-config.json";

        private static Snapshot _cached;

        public static string Path => System.IO.Path.Combine(Application.streamingAssetsPath, FileName);

        /// <summary>Loads and caches the snapshot. Pass <c>true</c> to force a re-read from disk.</summary>
        public static Snapshot Load(bool reload = false)
        {
            if (_cached != null && !reload) return _cached;

            var path = Path;
            if (!File.Exists(path))
            {
                Debug.LogError(
                    $"TheBlockConfig: {path} is missing. Run tools/export-config.sh to generate it.");
                return null;
            }

            var snapshot = JsonConvert.DeserializeObject<Snapshot>(File.ReadAllText(path));
            if (snapshot?.Config == null)
            {
                Debug.LogError($"TheBlockConfig: {path} parsed but has no `config` object.");
                return null;
            }

            _cached = snapshot;
            return _cached;
        }

        /// <summary>The exporter's envelope: provenance fields plus the config itself.</summary>
        public class Snapshot
        {
            [JsonProperty("$generator")] public string Generator;
            [JsonProperty("$source")] public string Source;
            [JsonProperty("$sourceSha256")] public string SourceSha256;
            [JsonProperty("$handedness")] public string Handedness;
            [JsonProperty("config")] public Root Config;
        }

        /// <summary>Mirrors the top level of <c>config.ts</c>. Only the ported sections are declared.</summary>
        public class Root
        {
            public CitySpec City;
            public List<DistrictSpec> Districts;
            public PlaceSpec PizzaPlace;
            public PlaceSpec GasStation;
            public PlaceSpec PoliceStation;
            public PlaceSpec SevenEleven;
        }

        /// <summary>A three.js <c>{x, y, z}</c> literal. Still right-handed — convert before use.</summary>
        public struct Vec3
        {
            public float X;
            public float Y;
            public float Z;

            /// <summary>The raw three.js vector, unconverted. Feed it to <see cref="Convert.Pos(Vector3)"/>.</summary>
            public Vector3 Raw => new Vector3(X, Y, Z);
        }

        /// <summary>Downtown. Unlike the other districts it carries the facade tint list.</summary>
        public class CitySpec
        {
            public string Url;
            public string Name;
            public float Scale = 1f;
            public Vec3 Position;

            /// <summary>Material names the web build recolours at load. Unity binds a material asset instead.</summary>
            public List<string> FacadeMaterials;

            /// <summary>Substrings that mark a mesh as foliage: rendered, never collided with.</summary>
            public List<string> NoCollidePatterns;
        }

        /// <summary>An outlying district GLB, offset from downtown.</summary>
        public class DistrictSpec
        {
            public string Url;
            public string Name;
            public float Scale = 1f;
            public Vec3 Position;

            /// <summary>Materials whose meshes are hidden outright — the baked-in parked cars.</summary>
            public List<string> HideMaterials;

            public List<string> NoCollidePatterns;
        }

        /// <summary>A placed landmark: the pizzeria, gas station, police station, 7-Eleven.</summary>
        public class PlaceSpec
        {
            public string Url;
            public string Name;
            public float Scale = 1f;
            public Vec3 Position;

            /// <summary>Yaw in radians, right-handed. Use <see cref="Convert.RotFromRadians"/>.</summary>
            public float Yaw;

            public List<string> HideNodes;
            public List<string> NoCollideNodes;

            /// <summary>When set, only meshes topping out at or below this height get a collider.</summary>
            public float? CollideMaxY;
        }
    }
}
